---
- project:
    name: of-config-sodium
    jobs:
      - odl-maven-jobs

    stream: sodium
    project: 'of-config'
    project-name: 'of-config'
    branch: 'master'
    mvn-settings: 'of-config-settings'
    mvn-opts: '-Xmx1024m -XX:MaxPermSize=256m'
    dependencies: netconf-merge-{stream}'
    email-upstream: '[of-config] [netconf]'

    # Used by the release job
    staging-profile-id: a6880455efe67

- project:
    name: of-config-neon
    jobs:
      - odl-maven-jobs

    stream: neon
    project: 'of-config'
    project-name: 'of-config'
    branch: 'stable/neon'
    mvn-settings: 'of-config-settings'
    mvn-opts: '-Xmx1024m -XX:MaxPermSize=256m'
    dependencies: netconf-merge-{stream}'
    email-upstream: '[of-config] [netconf]'

    # Used by the release job
    staging-profile-id: a6880455efe67

- project:
    name: of-config-fluorine
    jobs:
      - odl-maven-jobs

    stream: fluorine
    project: 'of-config'
    project-name: 'of-config'
    branch: 'stable/fluorine'
    mvn-settings: 'of-config-settings'
    mvn-opts: '-Xmx1024m -XX:MaxPermSize=256m'
    dependencies: netconf-merge-{stream}'
    email-upstream: '[of-config] [netconf]'

    # Used by the release job
    staging-profile-id: a6880455efe67

- project:
    name: of-config-oxygen
    jobs:
      - '{project-name}-distribution-check-{stream}'
      - odl-maven-jobs

    stream: oxygen
    project: 'of-config'
    project-name: 'of-config'
    branch: 'stable/oxygen'
    mvn-settings: 'of-config-settings'
    mvn-opts: '-Xmx1024m -XX:MaxPermSize=256m'
    dependencies: netconf-merge-{stream}'
    email-upstream: '[of-config] [netconf]'

    # Used by the release job
    staging-profile-id: a6880455efe67

- project:
    name: of-config-sonar
    jobs:
      - gerrit-maven-sonar
    project: 'of-config'
    project-name: 'of-config'
    branch: 'master'
    mvn-settings: 'of-config-settings'
    mvn-opts: '-Xmx1024m -XX:MaxPermSize=256m'

- project:
    name: of-config-view
    views:
      - project-view
    project-name: of-config
