---
- project:
    name: of-config-csit-basic
    jobs:
      - inttest-csit-verify-1node
      - inttest-csit-1node

    # The project name
    project: 'of-config'

    # The functionality under test
    functionality: 'basic'

    # Project branches
    stream:
      - oxygen:
          branch: 'master'
      - nitrogen:
          branch: 'stable/nitrogen'
      - carbon:
          branch: 'stable/carbon'
          karaf-version: karaf3

    install:
      - all:
          scope: 'all'

    # Features to install
    install-features: 'odl-restconf,odl-of-config-all,odl-of-config-rest'

    # Robot custom options
    robot-options: ''
