---
- project:
    name: of-config-phosphorus
    jobs:
      - odl-maven-jobs
      - odl-maven-verify-jobs

    stream: phosphorus
    project: "of-config"
    project-name: "of-config"
    branch: "master"
    mvn-settings: "of-config-settings"
    mvn-opts: "-Xmx1024m"
    dependencies: netconf-merge-{stream}'
    email-upstream: "[of-config] [netconf]"
    disable-job: true

    # Used by the release job
    staging-profile-id: a6880455efe67

- project:
    name: of-config-silicon
    jobs:
      - odl-maven-jobs
      - odl-maven-verify-jobs

    stream: silicon
    project: "of-config"
    project-name: "of-config"
    branch: "stable/silicon"
    mvn-settings: "of-config-settings"
    mvn-opts: "-Xmx1024m"
    dependencies: netconf-merge-{stream}'
    email-upstream: "[of-config] [netconf]"
    disable-job: true

    # Used by the release job
    staging-profile-id: a6880455efe67

- project:
    name: of-config-aluminium
    jobs:
      - odl-maven-jobs
      - odl-maven-verify-jobs

    stream: aluminium
    project: "of-config"
    project-name: "of-config"
    branch: "stable/aluminium"
    mvn-settings: "of-config-settings"
    mvn-opts: "-Xmx1024m"
    dependencies: netconf-merge-{stream}'
    email-upstream: "[of-config] [netconf]"
    disable-job: true

    # Used by the release job
    staging-profile-id: a6880455efe67

- project:
    name: of-config-release-management
    jobs:
      - gerrit-release-merge

    project: of-config
    project-name: of-config

    build-node: centos7-builder-2c-1g
    mvn-settings: of-config-settings

- project:
    name: of-config-sonar
    jobs:
      - gerrit-maven-sonar
    project: "of-config"
    project-name: "of-config"
    branch: "master"
    mvn-settings: "of-config-settings"
    mvn-opts: "-Xmx1024m"
    disable-job: true
    sonarcloud: true
    sonarcloud-project-organization: "{sonarcloud_project_organization}"
    sonarcloud-api-token: "{sonarcloud_api_token}"
    sonarcloud-project-key: "{sonarcloud_project_organization}_{project-name}"

- project:
    name: of-config-info
    jobs:
      - gerrit-info-yaml-verify
    project: of-config
    project-name: of-config
    branch: master
    build-node: centos7-builder-2c-1g

- project:
    name: of-config-view
    views:
      - project-view
    project-name: of-config
