---
- project:
    name: of-config-aluminium
    jobs:
      - gerrit-release-merge
      - odl-maven-jobs
      - odl-maven-verify-jobs

    stream: aluminium
    project: 'of-config'
    project-name: 'of-config'
    branch: 'master'
    mvn-settings: 'of-config-settings'
    mvn-opts: '-Xmx1024m'
    dependencies: netconf-merge-{stream}'
    email-upstream: '[of-config] [netconf]'
    disable-job: true

    # Used by the release job
    staging-profile-id: a6880455efe67

- project:
    name: of-config-magnesium
    jobs:
      - odl-maven-jobs
      - odl-maven-verify-jobs

    stream: magnesium
    project: 'of-config'
    project-name: 'of-config'
    branch: 'stable/magnesium'
    mvn-settings: 'of-config-settings'
    mvn-opts: '-Xmx1024m'
    dependencies: netconf-merge-{stream}'
    email-upstream: '[of-config] [netconf]'
    disable-job: true

    # Used by the release job
    staging-profile-id: a6880455efe67

- project:
    name: of-config-sodium
    jobs:
      - odl-maven-jobs
      - odl-maven-verify-jobs

    stream: sodium
    project: 'of-config'
    project-name: 'of-config'
    branch: 'stable/sodium'
    mvn-settings: 'of-config-settings'
    mvn-opts: '-Xmx1024m'
    dependencies: netconf-merge-{stream}'
    email-upstream: '[of-config] [netconf]'
    disable-job: true

    # Used by the release job
    staging-profile-id: a6880455efe67

- project:
    name: of-config-neon
    jobs:
      - odl-maven-jobs
      - odl-maven-verify-jobs

    stream: neon
    project: 'of-config'
    project-name: 'of-config'
    branch: 'stable/neon'
    mvn-settings: 'of-config-settings'
    mvn-opts: '-Xmx1024m'
    dependencies: netconf-merge-{stream}'
    email-upstream: '[of-config] [netconf]'
    disable-job: true

    # Used by the release job
    staging-profile-id: a6880455efe67

- project:
    name: of-config-sonar
    jobs:
      - gerrit-maven-sonar
    project: 'of-config'
    project-name: 'of-config'
    branch: 'master'
    mvn-settings: 'of-config-settings'
    mvn-opts: '-Xmx1024m'
    disable-job: true

- project:
    name: of-config-view
    views:
      - project-view
    project-name: of-config
