---
- project:
    name: ansible
    jobs:
      - '{project-name}-distribution-check-{stream}'
      - '{project-name}-maven-javadoc-jobs'
      - gerrit-tox-verify
      - odl-maven-jobs
      - odl-maven-verify-jobs

    stream:
      - aluminium:
          branch: 'master'
      - magnesium:
          branch: 'stable/magnesium'
      - sodium:
          branch: 'stable/sodium'

    project: ansible
    project-name: ansible
    mvn-settings: 'netvirt-settings'
    mvn-opts: '-Xmx2048m'
    build-node: centos7-builder-2c-2g
    build-timeout: 60
    staging-profile-id: 'da5a90345bd62'

- project:
    name: ansible-view
    views:
      - project-view
    project-name: ansible
