- project:
    name: openflowplugin-csit-config-performance-lithium-redesign-old
    jobs:
        - '{project}-csit-1node-{functionality}-{install}-{stream}'

    # The project name
    project: 'openflowplugin'

    # The functionality under test
    functionality: 'config-performance-lithium-redesign'

    # Project branches
    stream:
        - beryllium:
            branch: 'stable/beryllium'
            jre: 'openjdk7'

    install:
        - only:
            scope: 'only'

    # Features to install
    install-features: 'odl-openflowplugin-flow-services-ui-li'

    # Robot custom options
    robot-options: ''

    # Trigger jobs (upstream dependencies)
    trigger-jobs: 'yangtools-distribution-{stream},controller-distribution-{stream},openflowjava-distribution-{stream},openflowplugin-distribution-{stream}'

    # Plot Info
    01-plot-title: 'Flow REST API Rate'
    01-plot-yaxis: 'http_req/sec'
    01-plot-group: 'Flow Config Performance'
    01-plot-data-file: 'rates.csv'
    02-plot-title: 'Flow Stats Collect Time'
    02-plot-yaxis: 'seconds'
    02-plot-group: 'Stats Collect Performance'
    02-plot-data-file: 'times.csv'
